title: Polygon
description: Fonts and things
theme: just-the-docs

url: https://polyg.online

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout
